server:
  port: 0

spring:
  application:
    name: shopping-cart
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/cart
    username: shoppingCart
    password: shoppingCart

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

logging:
  level:
    root: INFO
    org:
      zalando:
        logbook: TRACE
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    your.application.package: DEBUG

