server:
  port: 0

spring:
  application:
    name: delivery
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6546/delivery
    username: delivery
    password: delivery
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true