server:
  port: 0

spring:
  application:
    name: order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6547/order
    username: order
    password: order
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true