spring:
  application:
    name: aggregator

kafka:
  sensor-topic: telemetry.sensors.v1
  snapshot-topic: telemetry.snapshots.v1
  bootstrap-servers: localhost:9092
  group-id: aggregator-group
  auto-commit: false

logging:
  level:
    org:
      zalando:
        logbook: DEBUG

